# 项目名称，唯一，尽量简洁，不要太长，后续 docker image tag、yaml配置、部署相关会用到
name: java-project
# 项目版本号，遵循 Semver 规范 (https://semver.org) -> 主版本号.次版本号.修订号 ，docker image tag、yaml配置
version: 0.0.1
# 项目简介，唯一，docker image tag、yaml配置
description: 项目简介
# 项目语言
programLanguage: java
# 项目分组，给项目分类，相同分类的项目docker image会放在同一个分组下
group: java-repos
# 项目构建流程
# shell-spec: 标准shell构建，完全使用hook来组装流程
# php-spec: 标准php构建，php-fpm + nginx -> docker
# java-spec: 标准java构建，java-jar -> docker
# web-spec: 标准web构建，nodejs -> dist
pipeline: shell-spec
# 用于build项目的docker镜像
buildImage: maven:3.6-openjdk-11
# build 命令
buildCommand: mvn clean package -Dfile.encoding=UTF-8 -DskipTests=true
# Hook，直接执行 shell，用来扩展增强构建流程
pipelineHook:
  buildBefore: |
    echo 'hook:buildBefore'
  buildAfter: |
    echo 'hook:buildAfter'
  dockerBefore: |
    echo 'hook:dockerBefore'
  dockerAfter: |
    echo 'hook:dockerAfter'
  deployBefore: |
    echo 'hook:deployBefore'
  deployAfter: |
    echo 'hook:deployAfter'