# 项目名称，唯一，尽量简洁，不要太长，后续 docker image tag、yaml配置、部署相关会用到
name: is-account
# 项目版本号，遵循 Semver 规范 (https://semver.org) -> 主版本号.次版本号.修订号 ，docker image tag、yaml配置
version: 0.0.36
# 项目简介，唯一，docker image tag、yaml配置
description: 账户服务
# 项目语言
program_language: java
# 项目构建流程
# shell-spec: 标准shell构建，完全使用hook来组装流程
# php-spec: 标准php构建，php-fpm + nginx -> docker
# java-spec: 标准java侯建，java-jar -> docker
pipeline: shell-spec
# 构建hook, 用来扩展增强构建流程
pipeline_hook:
  build_before: |
    echo 'hook:build_before'
  build_after: |
    echo 'hook:build_after'
  docker_image_before: |
    echo 'hook:docker_image_before'
  docker_image_after: |
    echo 'hook:docker_image_after'
  docker_push_before: |
    echo 'hook:docker_push_before'
  docker_push_after: |
    echo 'hook:docker_push_after'
  deploy_before: |
    echo 'hook:deploy_before'
  deploy_after: |
    echo 'hook:deploy_after'